[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18.20.2" }

[dev]
  command = "npm run dev"
  port = 3002

# Install Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Fallback for missing images
[[redirects]]
  from = "/placeholder*"
  to = "/pexels-ifaw-5487067.jpg"
  status = 200

# API proxy - redirect to backend
[[redirects]]
  from = "/api/*"
  to = "https://rescueradar-backend.vercel.app/api/:splat"
  status = 200
  force = true

# SPA fallback - important for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  condition = "!req.headers.accept || req.headers.accept.includes(\"text/html\")"

# Cache headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
